spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jwt_security
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

